name: Kernel Build Debug
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
